# Generated by Django 4.0.2 on 2022-02-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_order_alter_customer_user_orderitem_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('In queue', 'In queue'), ('Cooking', 'Cooking'), ('Waiting deliverer', 'Waiting deliverer'), ('On delivery', 'On delivery'), ('Finished', 'Finished')], default='In queue', max_length=50),
        ),
    ]
