# Generated by Django 4.0.2 on 2022-02-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_order_deliverer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliverer',
        ),
    ]
